wkentaro/gdown

gdown/__init__.py

The current code caused a FileNotFoundError. e.g. `FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/checkpoints/2018-02-16_first-model.pth1pep1l0ctmp'` This is because the directory name was prepended twice. `osp.basename` prevents this double directory issue.

Fix tmp location (7f05b76)

---

README.md
gdown/cached_download.py
gdown/cli.py
gdown/download.py
setup.py

Dear Kentaro Wada,
I have added a proxy support for gdown simply by passing a proxy argument from command line to the request library. Therefore, it should support the common proxy types (including the socks and https).
Hope it helps.

Proxy support.

---

gdown/download.py
tests/test_download.py

This PR includes #34 
#32 breaks existing codes using gdown:
```
File "/home/pazeshun/apc_test_ws/src/jsk_apc/demos/grasp_fusion/ros/grasp_fusion/python/grasp_fusion_lib/data/utils.py", line 95, in download
gdown.download(url, temp_path, quiet=quiet)
TypeError: download() takes exactly 4 arguments (3 given)
```
This is because existing codes pass 3 arguments to download function while #32 adds new required argument `proxy`.
This PR fixes that by adding default value to proxy.

Fix download for when proxy is not passed for backward compatibility

---

gdown/download.py

For https://github.com/wkentaro/gdown/issues/26

Retrieve access denied error message

---

.github/workflows/ci.yml
gdown/cli.py
gdown/download.py

Close https://github.com/wkentaro/gdown/issues/38
For https://github.com/wkentaro/gdown/issues/43

Add cookies saved in home cache directory

---

gdown/cli.py

This allows the caller to programmatically determine whether gdown succeeded.

Return non-zero exit code on failure

---

setup.py

After I pip install `gdown` with `requests` version 2.2.0, `gdown` command outputs an error.
I think this is because requests[socks] extras_require is not added in old version of `requests`.
In this pull request, I add `requests[socks]>=2.12.0` to setup.py.
From `requests` 2.12.0, correct requests[socks] extras_require is added.
https://github.com/psf/requests/commit/dedf9064c6fae669995d0dc04081f93845ca9c42
The following is a log of the problem I was experiencing.
1. check if requests==2.2.1
```
user@61195c8ade5f:~/gdown$ pip show requests                                                         
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python 
as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January …
```

Set requests version to 2.12.0 or higher.

---

gdown/download.py

I am surprised that, this is not being used here. By passing User-Agent header, Google drive assumes the request is coming from a browser, and it avoids following errors.
Access denied with the following error:
Too many users have viewed or downloaded this file recently. Please
try accessing the file again later. If the file you are trying to
access is particularly large or is shared with many people, it may
take up to 24 hours to be able to view or download the file. If you
still can't access a file after 24 hours, contact your domain
administrator.
You may still be able to access the file from the browser:

Added fake user agent

---

setup.cfg

This is the only way I've found to reliably add the LICENSE to the sdist

Add license file to source distribution

---

README.md
gdown/cli.py
gdown/download.py

Solves #86 by adding a `verify` parameter to the `download` method, either a boolean to control whether the server's TLS certificate should be verified, or a string with a path to a CA bundle to use for verification purposes. This parameter defaults to `True`, but setting it to `False` is so available and useful during local development, testing, or with specific servers with troublesome certificate configurations. This also adds a `--no-verify` option to the gdown CLI.

Add control over the verification of the server's TLS certificate

---

README.md

Simple fix to update the Python example with the current API.

Update `use_cookies` arg in `download_folder` README example.

---

gdown/download_folder.py

Close https://github.com/wkentaro/gdown/issues/197
```
% gdown --folder 'https://drive.google.com/drive/folders/1fQrF9TapZVWrxiKmasMUbIMfPu-Kvv2J?usp=sharing'
Retrieving folder list
Processing file 1i_CrVrClbr_YNeiI50WGK8ccgpyiLg1J áéíóúñ.txt
Retrieving folder list completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1i_CrVrClbr_YNeiI50WGK8ccgpyiLg1J
To: /Users/wkentaro/Documents/gdown/áéíóúñ/áéíóúñ.txt
0.00B [00:00, ?B/s]
Download completed
```

Fix unicode error in gdown.download_folder

---

gdown/__init__.py
setup.py

Close https://github.com/wkentaro/gdown/issues/213

Put version string in __init__.py

---

gdown/download.py

This PR is used to fix the issue in #222 and #223 (I closed it as it is duplicate with 222)
I checked the issue list and found that others also meet the similar issue. A common place between @rmcpantoja and I is that the file to be downloaded is considered as a large file and will prompt a virus scan warning.
Therefore I checked the source code of gdown, and find the place that is used to process this case (https://github.com/wkentaro/gdown/blob/941200a9a1f4fd7ab903fb595baa5cad34a30a45/gdown/download.py#L32). I printed the output when call the download function with an url of a large file, and found that there is no "downloadForm".
If using a web browser and enter the link of a file, and inspect the code (such as the file I used: …

223 Modify download form tag to fix download issue

---

gdown/download.py

There was a small typo in the prompt that is shown before downloading a file in `--fuzzy` mode.

Fix typo: uriginal -> original

---

gdown/cli.py
gdown/download.py
gdown/download_folder.py

Close https://github.com/wkentaro/gdown/pull/294
Close https://github.com/wkentaro/gdown/pull/293
Close https://github.com/wkentaro/gdown/issues/291

Fix User-Agent to download and add --user-agent option

---

README.md
gdown/cli.py
gdown/download.py

Close https://github.com/wkentaro/gdown/pull/287
We can use chrome extension like [Get cookies.txt LOCALLY](https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc) to export and use it.
@7x11x13 Thank you for the suggestion. I find MozzilaCookieJar format more reasonable, so let's migrate to that.

Use MozillaCookieJar instead of json to save cookies

---

gdown/download.py

Close https://github.com/wkentaro/gdown/pull/273

Skip process only for gdrive files by breaking early

---

gdown/download_folder.py
gdown/parse_url.py

Close https://github.com/wkentaro/gdown/issues/303
This supports the case
1. original url redirects to gdrive
2. the location is outside of us (so url needs 'hl=en')

Retry with canonicalized url if original url is not gdrive url

---

gdown/download.py
gdown/parse_url.py

Fixes #43. They were a few attempts to solve this, but even with the latest `gdown==5.0.1` the download still fails. The fixes so far have concentrated on cookies, but failed to realize that the original report is for large files for which GDrive asks for user confirmation since it cannot perform a virus check.
This PR addresses this part by properly parsing the confirmation form.

Add extra pattern to extract url from download-form returned by Google Drive for a large file

---

gdown/cached_download.py
tests/test___main__.py
tests/test_cached_download.py

- Will support md5, sha1, sha256, ...
Usage:
```python
gdown.cached_download(
url=url,
md5="xxxx...xxxx",
)
gdown.cached_download(
url=url,
hash="md5:xxxx....xxxx",
)
gdown.cached_download(
url=url,
hash="sha1:xxxx....xxxx",
)
gdown.cached_download(
url=url,
hash="sha256:xxxx....xxxx",
)
```

Replace md5 with hash in cached_download function for any hash algorithm

---

gdown/download_folder.py
tests/test_download_folder.py

Close https://github.com/wkentaro/gdown/pull/310
Close https://github.com/wkentaro/gdown/discussions/309
In https://github.com/wkentaro/gdown/discussions/309, @o-laurent explained an interesting use case where he wants to select which file to download in a Google Drive folder based on its file name.
If you pass `skip_download=True` to `download_folder`, you can get list of files as list of tuple of (id, path, local_path).
After that you can just use `gdown.download` to download the ones you want.
```python
files = gdown.download_folder(..., skip_download=True)
for file in files:
if file.path.endswith(".txt"):
gdown.download(id=file.id, output=file.local_path)
```

Add dry_run option to download_folder to return the list of files without download

---

gdown/download_folder.py

Let's say that we want to check what's inside a folder named "output", if the folder "output" does not exist yet on the machine, it is created. This behavior does not seem useful to gdown practitioners.
Thanks a lot!

BUG: Download folder with "skip_download=True" creates an output folder

---

.github/workflows/ci.yml
tests/test___main__.py
tests/test_download.py

Close https://github.com/wkentaro/gdown/pull/320

Support Windows and macOS in tests

---

gdown/download.py

- More understandable.
- I found this via https://github.com/wkentaro/gdown/issues/350

Show resume progress bar from the middle

---

gdown/download.py

When downloading to the filesystem, retrieve the `Last-Modified` date from the HTTP headers and use it to set the on-disk `mtime` of the downloaded file.
I've implemented this unconditionally, but maybe this should be gated behind a `--mtimes` CLI (and python API) option?

Feature: preserve GDrive's last modified time when downloading

---

gdown/__main__.py
gdown/download.py
gdown/download_folder.py

- The `--continue` option can now be used with folders.
- When a download is being sent to a file, detect when the file to resume is complete (→ has its final name)
- Avoids 0-byte ranged transfers (which _still_ count against the shared folder's download limit!)
- Speeds up `--continue` (resume mode) for partially transferred folders containing lots of files.
- Especially useful when download allowances are very limited, e.g. Tor-proxied access, or very popular folders.
- Now uses the conventional `.part` suffix for tempfiles, to make life nicer with Linux desktop thumbnailers.
- Update command line arguments to match.

Feature: allow folders to be continued more usefully
