wkentaro/gdown

- .travis.yml
- gdown/__init__.py
Close #11
```bash
gdown https://drive.google.com/uc?id=0B9P1L--7Wd2vNm9zMTJWOGxobkU -O - --quiet | tar zxvf -
```
> Support writing stream to stdout with -O - as wget

- gdown/download.py
> Move tmp file instead of copying

- gdown/cached_download.py
- gdown/cli.py
- gdown/download.py
*Usage*
```
gdown https://drive.google.com/uc?id=0B_NiLAzvehC9R2stRmQyM3ZiVjQ  --speed 2MB
```
Close https://github.com/wkentaro/gdown/issues/23
> Add speed option to download

- gdown/download.py
> add indent_func for python2.7

- gdown/download.py
For https://github.com/wkentaro/gdown/issues/43#issuecomment-639034215
> Remove download_warning_ from cookies

- gdown/download.py
> Close session in download()

- gdown/download.py
Close https://github.com/wkentaro/gdown/issues/57
> Support giving directory as output

- gdown/download.py
Close https://github.com/wkentaro/gdown/issues/69
> Fix for stdout as output target

- gdown/download.py
Close https://github.com/wkentaro/gdown/issues/71
> Fix downloading without output (output is None)

- .github/workflows/ci.yml
- README.md
- gdown/download.py
> Improve error message when a sign-in page is shown

- gdown/cli.py
- gdown/download.py
- gdown/parse_url.py
Close https://github.com/wkentaro/gdown/issues/103
Close https://github.com/wkentaro/gdown/issues/94
Close https://github.com/wkentaro/gdown/issues/54
Close https://github.com/wkentaro/gdown/pull/76
Close https://github.com/wkentaro/gdown/pull/105
> Add --fuzzy to handle various url formats

- README.md
- gdown/cli.py
- gdown/download.py
Close https://github.com/wkentaro/gdown/issues/85
> Add --continue to resume from partially-downloaded file

- .github/workflows/ci.yml
- gdown/cli.py
- gdown/download.py
Close https://github.com/wkentaro/gdown/issues/141
> Allow space and quote in the filename

- gdown/download.py
For https://github.com/wkentaro/gdown/issues/43 https://github.com/wkentaro/gdown/issues/146
Thanks to @VKarpick
> Mitigate permission denied error with &confirm=t

- gdown/download.py
Close https://github.com/wkentaro/gdown/issues/153
> Use tempfile.mktemp for Windows

- .github/workflows/ci.yml
- README.md
- gdown/cli.py
Close https://github.com/wkentaro/gdown/pull/137
> Allow users to specify a file ID without `--id`

- gdown/download_folder.py
For https://github.com/wkentaro/gdown/pull/170
Close https://github.com/wkentaro/gdown/issues/174
> Fix remaining_ok flag usage for recursive parsing

- gdown/download_folder.py
Close https://github.com/wkentaro/gdown/pull/170
> Fix folder_name with endash (happens in the UK)

- gdown/download_folder.py
Close https://github.com/wkentaro/gdown/issues/220
Close https://github.com/wkentaro/gdown/pull/210
Close https://github.com/wkentaro/gdown/pull/199
Close https://github.com/wkentaro/gdown/issues/205
Close https://github.com/wkentaro/gdown/issues/201
> Canonicalize language setting by ?hl=en

- gdown/cli.py
- gdown/download_folder.py
Some changes to make `verify`/`--no-check-certificate` options work with folders too.
> Add verify option for downloading folders

- gdown/download.py
Close https://github.com/wkentaro/gdown/issues/237
> Stop saving cookies_file when use_cookies=False

- gdown/download_folder.py
Close https://github.com/wkentaro/gdown/issues/232
> Catch DeprecationWarning from gdown.download_folder

- gdown/download.py
Close https://github.com/wkentaro/gdown/issues/237#issuecomment-1427446909
> Make ~/.cache/gdown only when necessary

- gdown/download.py
- gdown/download_folder.py
Close https://github.com/wkentaro/gdown/issues/227
> Support proxy in download_folder

- .github/workflows/ci.yml
- gdown/__init__.py
- gdown/_indent.py
- gdown/cached_download.py
- gdown/cli.py
- gdown/download.py
- gdown/download_folder.py
- gdown/exceptions.py
Close https://github.com/wkentaro/gdown/pull/246
Close https://github.com/wkentaro/gdown/discussions/169
> Raise and handle exceptions

- gdown/cached_download.py
- gdown/download.py
> Make log messages in download customizable

- .github/workflows/ci.yml
For https://github.com/wkentaro/gdown/issues/314#issuecomment-1925434057
cc @RunDevelopment
> Run GitHub Actions on macOS, Ubuntu, and Windows

- gdown/download.py
* I updated the description for the output parameter to indicate that it can be a directory 
* Currently it only shows it can be the file name 
* Original PR to make the code change is #66
> Trivial: Update the documentation for the output param
